accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # /accounts/signup/
    path('signup/', views.signup, name='signup'),
    # /accounts/signup/tourist/
    path('signup/tourist/', views.signup_tourist, name='signup_tourist'),
    # /accounts/signup/guide/
    path('signup/guide/', views.signup_guide, name='signup_guide'),
    
    # /accounts/login/
    path('login/', views.login, name='login'),
    # /accounts/logout/
    path('logout/', views.logout, name='logout'),
    
    # /accounts/harper/
    path('<str:username>/', views.profile, name='profile'),
    # /accounts/harper/wishlist/
    path('<str:username>/wishlist/', views.wishlist, name='wishlist'),
    # /accounts/harper/delete/
    path('<str:username>/delete/', views.delete, name='delete'),
]

sw_camp_project/urls.py
from django.contrib import admin
from django.urls import path, include

def home(request):
    from django.shortcuts import redirect
    return redirect('tour:product_index')

urlpatterns = [
    path('', home, name='home'), # home 추가
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tour/', include('tour.urls')),
]

tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    # /tour/
    path('', views.product_index, name='product_index'),
    
    # /tour/create/ 상품 생성
    path('create/', views.create_product, name='create_product'),
    # /tour/1/ 상품 정보
    path('<int:product_pk>/', views.product_detail, name='product_detail'),
    # /tour/1/update/ 상품 수정
    path('<int:product_pk>/update/', views.update_product, name='update_product'),
    # /tour/1/delete/ 상품 삭제
    path('<int:product_pk>/delete/', views.delete_product, name='delete_product'),
    
    # /tour/1/reviews/create/ 리뷰 작성
    path('<int:product_pk>/reviews/create/', views.create_review, name='create_review'),
    # /tour/1/reviews/1/delete/ 리뷰 삭제
    path('<int:product_pk>/reviews/<int:review_pk>/delete/', views.delete_review, name='delete_review'),
    
    # /tour/1/wishlist/ 위시리스트
    path('<int:product_pk>/wishlist/', views.wishlist, name='wishlist'),
    
    # /tour/1/proposal/ 투어 요청
    path('<int:product_pk>/proposal/', views.proposal_tour, name='proposal_tour'),
    # /tour/1/accept/ 투어 수락
    path('<int:product_pk>/accept/', views.accept_proposal, name='accept_proposal'),
    
    # /tour/search/
    path('search/', views.search, name='search'),

    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_countries.fields import CountryField

from django.utils import timezone

class User(AbstractUser):
    group_choices=[
            ('tourist', '투어리스트'),
            ('guide', '가이드'),
        ]
    
    guides = models.ManyToManyField('self', symmetrical=False, related_name='tourists', blank=False)
    
    
    group = models.CharField(choices=group_choices, max_length=10)
    email = models.EmailField(
        max_length=100, 
        null=False,
        unique=True, 
        blank=True
        )
    phone = models.CharField(max_length=11)
    country = CountryField(blank_label='select country', default=' ')
    city = models.CharField(max_length=50, default=' ')
    language = models.CharField(max_length=20, default=' ')
    is_guide = models.BooleanField(default=False)
    is_tourist = models.BooleanField(default=False)
    date_joined = models.DateField(default=timezone.now)
    

    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
# from django.contrib.auth.hashers import check_password

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(max_length=20)
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'phone', 
                  'country', 'city', 'language', )

# class CheckPasswordForm(forms.Form):
#     password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
#         attrs={'class': 'form-control',}
#     ))
    
#     def clean(self):
#         cleaned_data = super().clean()
#         password = cleaned_data.get('password')
#         confirm_password = self.user.password
        
#         if password:
#             if not check_password(password, confirm_password):
#                 self.add_error('password', '비밀번호가 일치하지 않습니다.')

accounts/views.py
# accounts/views.py

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_safe, require_POST
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout, get_user_model
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
# from .forms import CheckPasswordForm

from django.contrib.auth.models import Group

User = get_user_model()

# 회원가입 그룹 선택
@require_http_methods(['GET', 'POST'])
def signup(request):
    return render(request, 'accounts/signup.html')


# "가이드" 회원가입
@require_http_methods(['GET', 'POST'])
def signup_guide(request):
            
    if request.method == 'GET':
        form = CustomUserCreationForm()
    else:
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            # Group = request.user.groups.filter(name='guide') 
            group = Group.objects.get(name='guide')
            user.groups.add(group)
    
            auth_login(request, user)
            return redirect('home')
    
    return render(request, 'accounts/signup_guide.html', {
        'form': form,
    })
    
# "투어리스트" 회원가입
@require_http_methods(['GET', 'POST'])
def signup_tourist(request):
    # if not request.user.groups.filter(name="tourist").exists():
    #     return redirect('home')
    
    if request.method == 'GET':
        form = CustomUserCreationForm()
    else:
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            # Group = request.user.groups.filter(name='tourist') 
            group = Group.objects.get(name='tourist')
            user.groups.add(group)
            
            auth_login(request, user)
            return redirect('home')
    
    return render(request, 'accounts/signup_tourist.html', {
        'form': form,
    })

# 로그인
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'GET':
        form = AuthenticationForm()
    else:              
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'home')
    return render(request, 'accounts/login.html', {
        'form': form,
    })

# 로그아웃
def logout(request):
    auth_logout(request)
    messages.success(request, "로그아웃 되었습니다.")
    return redirect('home')

# 프로필 창
@require_safe
def profile(request, username):
    profile_user = get_object_or_404(User, username=username)
    # like_guide = request.user.guides.filter(pk=profile_user.pk).exists()
    
    return render(request, 'accounts/profile.html', {
        'profile_user': profile_user,
        # 'like_guide': like_guide,
    })

# 찜하기
@require_POST
@login_required
def wishlist(request, username):  # follow=wishlist, guide = star, tourist = fan
    
    guide = get_object_or_404(User, username=username)  # User = get_user_model() 위에 참조
    tourist = request.user
    
    if guide != tourist:  
    
        # 기존에 찜 한 사람이라면 취소, 아니라면 찜 목록에 추가
        if tourist.guides.filter(pk=guide.pk).exists():
            # 기존에 찜한 적 있으면 취소
            tourist.guides.remove(guide)  
        else:
            # 찜 한 적 없으면 위시리스트에 추가
            tourist.guides.add(guide)  

    return redirect('accounts:profile', guide)  # 가이드(star.pk)의 프로필 페이지로 오기 


# 회원정보 수정
from django.contrib.auth.forms import UserChangeForm

@require_POST
def update(request):
    if request.method=='POST':
        pass
    else:
        form = UserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

# 비밀번호 변경
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        else:
            form = PasswordChangeForm(request.user)
            
        context = {
            'form': form,
        }
        return render(request, 'accounts/signup.html', context)  #


# 탈퇴하기
@require_POST
def delete(request, username):
    profile_user = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('accounts:login')

accounts/templates/accounts/login.html
<!-- accounts/login.html -->

<form method="POST">
  {% csrf_token %}
  <h2>로그인</h2>
  {{ form.as_p }}
  
  <div>
    <button class='btn btn-primary'>로그인</button>
  </div>
</form>

accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <!-- bootstrap-icon css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
  <ul>
    <h2 class="mx-3 my-5">{{ profile_user.username }} 의 프로필 - {{profile_user.group}}</h2>

    {% for group in groups %}
    {% if group.name == 'guide' %}
      <div>
        나를 찜한 유저: {{ profile_user.tourists.count }}
      </div>
    {% else %}
      <div>
        내가 찜한 가이드: {{ profile_user.guides.count }}
      </div>
    {% endif %}
    {% endfor %}


    <h3 class="mx-3 my-3">찜한 상품</h3>
    <ul>
      {% for product in profile_user.wish_products.all %}
      <li>
        <a href="{% url 'tour:product_detail' product.pk %}">
          {{ product.title }}
        </a>
      </li>
      {% endfor %}
    </ul>

    <hr>

    <h3 class="mx-3 my-3">작성한 후기</h3>
    <ul>
      {% for review in profile_user.reviews.all %}
      <li>
        <a href="{% url 'tour:product_detail' review.product.pk %}">
          {{ review.content }}
        </a>
      </li>
      {% endfor %}
    </ul>

    {% include 'accounts/profile_delete.html' %}


  </ul>

  <!-- bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/profile_delete.html
<!-- accounts/templates/accounts/profile_delete.html -->


{% if user.is_authenticated and profile_user == user %}

<ul>
  <div>
    <form action="{% url 'accounts:delete' profile_user.username %}" method="POST">
      {% csrf_token %}
      <button class='btn btn-danger mx-1 my-5'  onclick="return confirm('정말 탈퇴 하시겠습니까?')">탈퇴하기</button>
      
    </form>
  </div>
</ul>


{% endif %}

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <!-- bootstrap-icon css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
  <ul>
    <h2 class="mx-3 my-5">회원가입</h2>
    <ul style="display: flex; flex-wrap: wrap;">
      <a href="{% url 'accounts:signup_tourist' %}">
        <button class='btn btn-default btn-lg btn-primary'>투어리스트</button>
      </a>

      <a href="{% url 'accounts:signup_guide' %}">
        <button class='btn btn-default btn-lg btn-primary'>가이드</button>
      </a>
  </ul>
    
    {% comment %} <div>
        <a href="{% url 'accounts:signup_tourist' %}">
            <button class='btn btn-default btn-lg btn-primary'>투어리스트</button>
        </a>
    </div>
    
    <div>
        <a href="{% url 'accounts:signup_guide' %}">
            <button class='btn btn-default btn-lg btn-primary'>가이드</button>
        </a>
    </div> {% endcomment %}
   
  </ul>

  <!-- bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/signup_guide.html
<form method="POST">
    {% csrf_token %}
    
    {{ form.as_p }}
    <div>
      <button class='btn btn-primary'>가이드로 가입하기</button>
    </div>
</form>

accounts/templates/accounts/signup_tourist.html
<form method="POST">
    {% csrf_token %}
    
    {{ form.as_p }}
    <div>
      <button class='btn btn-primary'>투어리스트로 가입하기</button>
    </div>
</form>