accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # /accounts/signup/
    path('signup/', views.signup, name='signup'),
    # /accounts/signup/tourist/
    path('signup/tourist/', views.signup_tourist, name='signup_tourist'),
    # /accounts/signup/guide/
    path('signup/guide/', views.signup_guide, name='signup_guide'),
    
    # /accounts/login/
    path('login/', views.login, name='login'),
    # /accounts/logout/
    path('logout/', views.logout, name='logout'),
    
    # /accounts/harper/
    path('<str:username>/', views.profile, name='profile'),
    # /accounts/harper/wishlist/
    path('<str:username>/wishlist/', views.wishlist, name='wishlist'),
    # /accounts/harper/delete/
    path('<str:username>/delete/', views.delete, name='delete'),
]

sw_camp_project/urls.py
from django.contrib import admin
from django.urls import path, include

def home(request):
    from django.shortcuts import redirect
    return redirect('tour:product_index')

urlpatterns = [
    path('', home, name='home'), # home 추가
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tour/', include('tour.urls')),
]

tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    # /tour/
    path('', views.product_index, name='product_index'),
    
    # /tour/create/ 상품 생성
    path('create/', views.create_product, name='create_product'),
    # /tour/1/ 상품 정보
    path('<int:product_pk>/', views.product_detail, name='product_detail'),
    # /tour/1/update/ 상품 수정
    path('<int:product_pk>/update/', views.update_product, name='update_product'),
    # /tour/1/delete/ 상품 삭제
    path('<int:product_pk>/delete/', views.delete_product, name='delete_product'),
    
    # /tour/1/reviews/create/ 리뷰 작성
    path('<int:product_pk>/reviews/create/', views.create_review, name='create_review'),
    # /tour/1/reviews/1/delete/ 리뷰 삭제
    path('<int:product_pk>/reviews/<int:review_pk>/delete/', views.delete_review, name='delete_review'),
    
    # /tour/1/wishlist/ 위시리스트
    path('<int:product_pk>/wishlist/', views.wishlist, name='wishlist'),
    
    # /tour/1/proposal/ 투어 요청
    path('<int:product_pk>/proposal/', views.proposal_tour, name='proposal_tour'),
    # /tour/1/accept/ 투어 수락
    path('<int:product_pk>/accept/', views.accept_proposal, name='accept_proposal'),
    
    # /tour/search/
    path('search/', views.search, name='search'),

    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <!-- bootstrap-icon css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
  {% include 'navbar.html' %}

  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<!-- base_nav.html -->

<nav class="navbar fixed-top navbar-expand-lg bg-dark"> <!--fixed-top-->
  <div class="container-fluid">

    <li>
      <a class='navbar-brand text-white' href="{% url 'home' %}">Home</a>
    </li>

    <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
      <ul class='navbar-nav'>
        {% if user.is_authenticated %} 
        
        {% for group in user.groups.all %}
        {% if group.name == 'guide' %}
        <li>
          <a class='nav-link text-white active' aria-current='page' href="{% url 'tour:create_product' %}" method="POST">Product</a>
        </li>
        
        {% endif %}
        {% endfor %}
        <li>
          <a class='nav-link text-white active' aria-current='page' href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        
        <li>
          <a class='nav-link text-white active' aria-current='page' href="{% url 'accounts:profile' user %}">{{ user }}'s Profile</a>
        </li>
        {% else %}
        <li class="nav-item">
          {% if not user.is_authenticated %}
          <a class="nav-link text-white active" aria-current="page" href="{% url 'accounts:signup' %}">Signup</a>
          {% endif %}
        </li>
        <li>
          <a class="nav-link text-white active" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>

    <!--검색창 -->
    <nav class="navbar bg-dark border-bottom-dark" data-bs-theme="dark">
      <div class="container-fluid d-flex justify-content-end">
        <form class="d-flex" method="POST" action="{% url 'tour:search' %}" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
          {% csrf_token %}
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </nav>

  </div>
</nav>

<!-- Carousel -->
<div id="carousel" class="carousel slide h-50" data-bs-ride="carousel">
  <div class="carousel-inner">
    <style>
      /* 캐러셀(이미지슬라이드) 이미지 크기변경 */
      .carousel-inner{
        width:300;
        height:600px; /* 이미지 높이 변경 */
      }
      .carousel-item{
        width: 300;
        height:100%;
      }
      .d-block {
        display:block;
        width: 300;
        height: 100%;
      }
    </style>
    <div class="carousel-item active">
      <img src="https://cdn.imweb.me/upload/S2017101359e025984d346/268b00e48f9bc.jpg" class="d-block w-100 " alt="italy">
    </div>
    <div class="carousel-item">
      <img src="https://img1.daumcdn.net/thumb/R1280x0/?fname=http://t1.daumcdn.net/brunch/service/user/278i/image/qyv4ZBV_iPEL1g_iAoQyuBQNyn8.jpg" class="d-block w-100" alt="swiss">
    </div>
    <div class="carousel-item">
      <img src="https://youimg1.tripcdn.com/target/0106l120008x0rybg3168_C_640_320_R5_Q70.jpg_.webp?proc=source%2Ftrip" class="d-block w-100" alt="finland">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>