accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # /accounts/signup/
    path('signup/', views.signup, name='signup'),
    # /accounts/signup/tourist/
    path('signup/tourist/', views.signup_tourist, name='signup_tourist'),
    # /accounts/signup/guide/
    path('signup/guide/', views.signup_guide, name='signup_guide'),
    
    # /accounts/login/
    path('login/', views.login, name='login'),
    # /accounts/logout/
    path('logout/', views.logout, name='logout'),
    
    # /accounts/harper/
    path('<str:username>/', views.profile, name='profile'),
    # /accounts/harper/wishlist/
    path('<str:username>/wishlist/', views.wishlist, name='wishlist'),
    # /accounts/harper/delete/
    path('<str:username>/delete/', views.delete, name='delete'),
]

sw_camp_project/urls.py
from django.contrib import admin
from django.urls import path, include

def home(request):
    from django.shortcuts import redirect
    return redirect('tour:product_index')

urlpatterns = [
    path('', home, name='home'), # home 추가
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tour/', include('tour.urls')),
]

tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    # /tour/
    path('', views.product_index, name='product_index'),
    
    # /tour/create/ 상품 생성
    path('create/', views.create_product, name='create_product'),
    # /tour/1/ 상품 정보
    path('<int:product_pk>/', views.product_detail, name='product_detail'),
    # /tour/1/update/ 상품 수정
    path('<int:product_pk>/update/', views.update_product, name='update_product'),
    # /tour/1/delete/ 상품 삭제
    path('<int:product_pk>/delete/', views.delete_product, name='delete_product'),
    
    # /tour/1/reviews/create/ 리뷰 작성
    path('<int:product_pk>/reviews/create/', views.create_review, name='create_review'),
    # /tour/1/reviews/1/delete/ 리뷰 삭제
    path('<int:product_pk>/reviews/<int:review_pk>/delete/', views.delete_review, name='delete_review'),
    
    # /tour/1/wishlist/ 위시리스트
    path('<int:product_pk>/wishlist/', views.wishlist, name='wishlist'),
    
    # /tour/1/proposal/ 투어 요청
    path('<int:product_pk>/proposal/', views.proposal_tour, name='proposal_tour'),
    # /tour/1/accept/ 투어 수락
    path('<int:product_pk>/accept/', views.accept_proposal, name='accept_proposal'),
    
    # /tour/search/
    path('search/', views.search, name='search'),

    
]

tour/models.py
from django.db import models
from django.conf import settings
from django_countries.fields import CountryField
from django.utils import timezone

class Product(models.Model):
    theme_choices=[
            ('힐링', '힐링'),
            ('문화체험', '문화체험'),
            ('액티비티', '액티비티'), 
            ('역사 가이드', '역사 가이드'),
        ]
    
    personned_choices=[
            (1, '1'),
            (2, '2'),
            (3, '3'), 
            (4, '4'),
            (5, '5'), 
            (6, '6'),
            (7, '7'),
            (8, '8'), 
            (9, '9'),
            (15, '10 or more'),
        ]
    
    title = models.CharField(max_length=200)
    content = models.TextField()
    
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='products')
    
    # image = models.ImageField(upload_to="", blank=False, null=False)
    
    country = CountryField(blank_label='select country')
    region = models.CharField(max_length=50, default=' ')
    theme = models.CharField(choices=theme_choices, max_length=30)
    max_personned = models.IntegerField(choices=personned_choices)
    
    # 찜하기
    wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='wish_products')
    
class Review(models.Model):
    score_choices = [
        (1, '1'),
        (2, '2'), 
        (3, '3'),
        (4, '4'), 
        (5, '5'),
    ]
    content = models.CharField(max_length=200)
    
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
   
    score = models.IntegerField(choices=score_choices)
    date = models.DateTimeField(default=timezone.now)  # auto_now=True


class Proposal(models.Model):
    personned_choices=[
            (1, '1'),
            (2, '2'),
            (3, '3'), 
            (4, '4'),
            (5, '5'), 
            (6, '6'),
            (7, '7'),
            (8, '8'), 
            (9, '9'),
            (15, '10 or more'),
        ]
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='proposals')
    tour_date = models.DateField(default=timezone.now)  # auto_now=True
    personned = models.IntegerField(choices=personned_choices)
    comment = models.CharField(max_length=500)
    
    # 요청 수락
    accept = models.BooleanField()
    
    
# class Accept(models.Model):
    
#     writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='accepts')
#     date = models.DateTimeField(default=timezone.now)  # auto_now=True

tour/forms.py
from django import forms
from .models import Product, Review, Proposal
# from django_countries.widgets import CountrySelectWidget
# from django_countries.fields import CountryField

class ProductForm(forms.ModelForm):
    title = forms.CharField(
        min_length=2,
        max_length=100,
        label = '투어 이름',
        widget=forms.TextInput(attrs={
            'placeholder': '내용을 입력해주세요',
        })
    )
    
    content = forms.CharField(
        min_length=2,
        widget=forms.Textarea(attrs={
            'placeholder': '투어 내용을 설명해주세요',
        }),
        label='투어 내용'
    )
    
    region = forms.CharField(
        widget=forms.Textarea(attrs={
            'placeholder': '지역을 선택해주세요',
        }),
    )
    
    
    class Meta:
        model = Product
        fields = ('title', 'content', 'country', 'region', 'theme', 'max_personned', ) # 'image',


class ReviewForm(forms.ModelForm):
    
    content = forms.CharField(
        max_length=200,
        widget=forms.Textarea(attrs={
            'placeholder': '최대 200자',
        }),
        label='Review'
    )
    
    class Meta:
        model = Review
        fields = ('score', 'content', )
        
        
class DateInput(forms.DateInput):
    input_type = 'date'
     
class ProposalForm(forms.ModelForm):
    comment = forms.CharField(
        max_length=500,
        widget=forms.Textarea(attrs={
            'placeholder': '가이드에게 하고 싶은 말을 적어주세요! ex) 1. 투어 원하는 시간 2. 해보고 싶은 것 3. 인원수'
        }),
        label='Proposal'
    )
    
    class Meta:
        model = Proposal
        widget = {
            'tour_date': DateInput(),
        }
        fields = ('tour_date', 'personned', 'comment', )

tour/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages

from django.core.paginator import Paginator
from django.db.models.aggregates import Avg

from .models import Product, Review, Proposal
from .forms import ProductForm, ReviewForm, ProposalForm

# 상품 등록
@login_required
@require_http_methods(['GET', 'POST'])
# @permission_required('tour.can_make_product')
def create_product(request):
    if not request.user.groups.filter(name="guide").exists():
        return redirect('home')
    
    if request.method == 'GET':
        form = ProductForm()
    else:
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.writer = request.user
            product.save()
            return redirect('tour:product_detail', product.pk)

    return render(request, 'tour/form.html',{
        'form': form,
    })

# 상품 4개씩 보이게 하기
@require_safe
def product_index(request):
    products = Product.objects.all()
    paginator = Paginator(products, 9)
    page_number = request.GET.get("page")
    
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'tour/index.html', {
        'page_obj': page_obj,
    })

# # 상품 10개씩 보이기
# @require_safe
# def product_index(request):
#     products = Product.objects.all()
#     paginator = Paginator(products, 10)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)
    
#     return render(request, 'tour/index.html', {
#         'page_obj': page_obj,
#     })

# 내 프로필 들어가서 상품 관련 정보 보이기
@require_safe
def product_detail(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    reviews = product.reviews.all()
    form = ReviewForm()
    
    avgscores = Review.objects.filter(product_id=product.pk).aggregate(average_score = Avg("score"))
    if avgscores['average_score'] != None:
        avgscores = round(avgscores['average_score'], 1)
    else:
        avgscores = 0.0
    
    is_wishlist = product.wishlist.filter(pk=request.user.pk)

    return render(request, 'tour/detail.html', {
        'product': product,
        'reviews': reviews,
        'form': form,
        'avgscore': avgscores,
        'is_wishlist': is_wishlist,
    })
    


# 상품 수정
@login_required
@require_http_methods(['GET', 'POST'])
def update_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    
    if request.user != product.writer:
        return redirect('tour:product_detail', product.pk)
    
    if request.method == 'GET':
        form = ProductForm(instance=product)
    else:
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = product.save()
            return redirect('tour:product_detail', product_pk)
    return render(request, 'tour/form.html', {
        'form': form
    })
    
# 상품 삭제
@login_required
@require_POST
def delete_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    
    if request.user != product.writer:
        return redirect('tour:product_detail', product.pk)
    product.delete()
    return redirect('tour:product_index')

# 리뷰 생성
@login_required
@require_POST
def create_review(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    form = ReviewForm(request.POST)

    if form.is_valid():
        review = form.save(commit=False)
        review.product = product
        review.writer = request.user
        review.save()
        return redirect('tour:product_detail', product.pk)

# 리뷰 삭제
@login_required
@require_POST
def delete_review(request, product_pk, review_pk):
    product = get_object_or_404(Product, pk=product_pk)
    review = get_object_or_404(Review, pk=review_pk)
    
    if request.user != review.writer:
        return redirect('tour:product_detail', product.pk)
    review.delete()
    return redirect('tour:product_detail', product.pk)
 
# 찜하기
@login_required
@require_POST
def wishlist(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    user = request.user
    
    if product.wishlist.filter(pk=user.pk).exists():
        product.wishlist.remove(user)
    else:
        product.wishlist.add(user)
    return redirect('tour:product_detail', product.pk)
   

# @login_required 
# def proposal_tour(request, product_pk):
#     product = get_object_or_404(Product, pk=product_pk)
#     proposal = request.user
#     # user = request.user
    
#     if request.user.is_authenticated:
#         if request.user != product.writer:
#             # 내 프로필에 신청 기록 띄우기
#             if product.proposal.filter(pk=proposal.pk).exists():
#                 product.proposal.remove(request.user)
#                 messages.add_message(proposal.request, messages.ERROR, '이미 신청된 투어입니다.')
#             else:
#                 product.proposal.add(proposal.pk)
#                 messages.add_message(proposal.reqeust, messages.SUCCESS, '신청이 완료되었습니다.')
#         return render('tour/tour_proposal') 
#     # 가이드 프로필에 제안 알림
    
#     return redirect('tour:product_detail', proposal.username)

# 투어 요청하기
@login_required 
def proposal_tour(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    proposal = request.user
    
    if request.user.is_authenticated:
        if request.user != product.writer:
            # 내 프로필에 신청 기록 띄우기
            if product.proposal.filter(pk=proposal.pk).exists():
                product.proposal.remove(request.user)
                messages.add_message(proposal.request, messages.ERROR, '이미 신청된 투어입니다.')
            else:
                product.proposal.add(proposal.pk)
                messages.add_message(proposal.request, messages.SUCCESS, '신청이 완료되었습니다.')
        return render(request, 'tour/tour_proposal.html') 
    # 가이드 프로필에 제안 알림
    
    return redirect('tour/product_detail/')

    
# 요청 수락하기
@login_required
def accept_proposal(request, proposal_pk):
    proposal = get_object_or_404(Proposal, pk=proposal_pk)
    
    if request.method == 'POST':
        if not request.user.is_authenticated:
            messages.error(request, '로그인이 필요합니다.')
            return redirect('accounts:login')
        
        if proposal.product.writer != request.user:
            messages.error(request, '예약 수락 권한이 없습니다.')
            return redirect('home')
        
        proposal.accepted = True
        proposal.save()
        messages.success(request, '예약을 수락했습니다.')

    return redirect('home')

# 요청 거절하기
@login_required
def reject_proposal(request, proposal_pk):
    proposal = get_object_or_404(Proposal, pk=proposal_pk)
    
    if request.method == 'POST':
        if not request.user.is_authenticated:
            messages.error(request, '로그인이 필요합니다.')
            return redirect('accounts:login')
        
        if proposal.product.writer != request.user:
            messages.error(request, '예약 거절 권한이 없습니다.')
            return redirect('home')
        
        proposal.delete()
        messages.success(request, '예약을 거절했습니다.')

    return redirect('home')


    
    # 수락한 요청 가이드 프로필에 띄우기
    
    # 투어리스트에게 안내 문자
    

@login_required
def search(request):
    if request.method == 'POST':  # POST 말고 GET으로 보내기
        searched = request.POST['searched']
        product = Product.objects.filter(country__contains=searched)
        return render(request, 'tour/search.html', {
            'searched': searched, 
            'product': product,})
    else:
        return render(request, 'tour/search.html', {})

tour/templates/tour/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <!-- bootstrap-icon css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>
<body>
  <ul>
    <h2>{{ product.title }} </h2>

    <h5 class="m-2">작성자 - {{ product.writer.username }}</h5>

    <h5 class="m-3">평점 : {{ avgscore }}  ({{ product.reviews.count }}개의 리뷰)</h5>
    <h6 class="m-3"><i class='bi bi-heart-fill' style='color: red'></i> {{ product.wishlist.count }}명이 이 상품을 좋아합니다.</h6>

    <h5 class="m-3"> <span class="badge bg-secondary">투어할 나라 / 지역</span></h5>
    <p class="m-3"> {{ product.country }} {{ product.region }}</p>

    <h5 class="m-3"><span class="badge bg-secondary">투어 일정</span></h5>
    <p class="m-3"> {{ product.content | linebreaksbr }}</p>

    <h5 class="m-3"><span class="badge bg-secondary">테마</span></h5>
    <p class="m-3"> {{ product.theme }}</p>

    <!-- 투어 요청하기 -->
    <h5 class="m-3"><span class="badge bg-primary">투어 요청하기</span></h5>
    {% include 'tour/tour_proposal.html' %}

    <!-- 찜 버튼 -->
    <h5 class="m-3"><span class="badge bg-secondary">찜하기</span></h5>
    {% include 'tour/detail_ui.html' %}

    <!-- 댓글 UI -->
    <h5 class="m-3"><span class="badge bg-secondary">리뷰</span></h5>
    {% include 'tour/detail_review_ui.html' %}

    

    

    {% comment %} {% if user.is_authenticated %}

    <div style="display: inline-block;">
      <form action="{% url 'tour:wishlist' product.pk %}" method="POST">
        {% csrf_token %}
        
        {% if is_wishlist %}
        <button class='btn btn-primary'>찜 취소</button>
        {% else %}
        <button class='btn btn-primary'>찜</button>
        {% endif %}
      </form>
    </div>

    {% endif %} {% endcomment %}

    
  </ul>

  <!-- bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

tour/templates/tour/detail_review_ui.html
<!-- detail_review_ui.html -->

{% load bootstrap5 %}


<ul>
  {% for review in reviews %}
  
  <li>
    <a href="{% url 'accounts:profile' review.writer.username %}">
      {{ review.writer.username }}
    </a>
    > {{ review.content }} [{{ review.score }}점] - {{ review.date }}
  </li>
  
  {% endfor %}
</ul>

<hr>

<!-- 리뷰 작성 -->
{% if user.is_authenticated %}
{% if user != product.writer %}
<p>
  <form action="{% url 'tour:create_review' product.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    <button class='btn btn-secondary'>작성</button>
  </form>
</p>
{% endif %}
{% endif %}

<hr>

<!-- 리뷰 삭제 -->
<ul>
  {% for review in reviews %}
  <li>
    <a href="{% url 'accounts:profile' review.writer.username %}">
      {{ review.writer.username }}
    </a>
    > {{ review.content }}

    {% if user == review.writer %}
    <form 
      action="{% url 'tour:delete_review' product.pk review.pk %}" 
      method="POST"
      style="display: inline-block;">
      {% csrf_token %}
      <button class='btn btn-danger' onclick="return confirm('삭제하시겠습니까?')">삭제</button>
    </form>
    {% endif %}

  </li>
  {% endfor %}
</ul>

tour/templates/tour/detail_ui.html
<!-- 상품 수정 버튼 -->
{% if user == product.writer %}
{% for group in user.groups.all %}
{% if group.name == 'guide' %}
<div>
    <a href="{% url 'tour:update_product' product.pk %}">
        <button class='btn btn-primary'>수정</button>
    </a>
</div>

<!-- 상품 삭제 버튼-->
<div>
    <form action="{% url 'tour:delete_product' product.pk %}" method="POST">
        {% csrf_token %}
        <button class='btn btn-primary' onclick='return confirm('삭제하시겠습니까?')'>삭제</button>
    </form>
</div>
{% endif %}
{% endfor %}
{% endif %}

<!-- 찜 -->
{% if user.is_authenticated %}

<div>
    <form action="{% url 'tour:wishlist' product.pk %}" method="POST">
        {% csrf_token %}
        {% if is_wishlist %}
        <button class='btn'>
            <i class='bi bi-heart-fill' style='color: red'></i>
        </button>
        {% else %}
        <button class='btn'>
            <i class='bi bi-heart'></i>
        </button>
        {% endif %}
    </form>
</div>

{% endif %}

tour/templates/tour/form.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <!-- bootstrap-icon css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <ul>
    <h2 class="mx-3 my-5">투어 등록하기</h2>
  </ul>
  
</head>
<body>
  <ul>
    <form method="POST">
        {% csrf_token %}
    
        {% bootstrap_form form %}
        
        <div>
            <button class='btn btn-secondary'>업로드</button>
        </div>
    </form>
  </ul>
  
  

  <!-- bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

tour/templates/tour/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<!-- 가이드 정보 -->
<ul>
  <h2 class="mx-3 my-5 d-flex justify-content-center">가이드를 선택해보세요!</h2>
  <ul style="display: flex; flex-wrap: wrap;">
    {% for product in page_obj %}
    
    <div style="margin: 0 16px">
      <div class="row col-sm-6 card m-3" style="width: 18rem;">
        {% comment %} <img src="{{ product.image.url }}" class="card-img-top" alt="..."> {% endcomment %}
        <div class="card-body" style="margin: 0 20px">
          <h5 class="card-title">{{ product.title }}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{ product.writer }}</h6>
          <p class="card-text"><i class='bi bi-star-fill' style='color: yellow'></i> {{ avgscore }}  ({{ product.reviews.count }}개의 리뷰)</p>
          <a href="{% url 'tour:product_detail' product.pk %}" class="position-bottom btn btn-secondary">자세히 보기</a>
        </div>
      </div>
    </div>
       
  
    {% endfor %}
  </ul>
</ul>
<!-- pagination 네비게이터 -->
<div class="mt-3 d-flex justify-content-center">
  {% bootstrap_pagination page_obj %}
</div>

{% comment %} <h2>Review</h2>

<ul>
  {% for product in page_obj %}
  <li>
     <a href="{% url 'accounts:profile' product.writer.username %}">
      {{ product.writer.username }}
    </a> >> 
    <a href="{% url 'tour:product_detail' product.pk %}">
      {{ product.content }}
    </a> ({{ product.reviews.count }})
  </li>
  {% endfor %}
</ul>

<!-- pagination 네비게이터 -->
<div class="mt-3 d-flex justify-content-center">
  {% bootstrap_pagination page_obj %}
</div> {% endcomment %}


{% endblock content %}

tour/templates/tour/search.html
{% extends 'base.html' %}
{% block content %}

    {% if searched %}
        <h2> 검색하신 {{searched}} 정보입니다. </h2>
        <br>
        {% for product in products %}  <!-- 검색 결과 여러개이기 때문에 반복문 사용-->

            {{ product.title }}
            {{ product.content }}
            {{ product.writer }}
            {{ product.country }}
            {{ product.region }}

        {% endfor %}

    {% else %}  <!-- 검색창에 아무것도 입력하지 않았을 경우-->
        <h2> 찾고 있는 나라/지역명 또는 가이드 이름을 검색해주세요.</h2>
    {% endif %}

{% endblock content %}

tour/templates/tour/tour_accept.html
{% if user == product.writer %}
{% for group in user.groups.all %}
{% if group.name == 'guide' %}
<div>
    <form action="{% url 'tour:accept_proposal' proposal.pk %}" method="POST">
        <div>
            <button>수락</button>
        </div>
    </form>

    <form action="{% url 'tour:reject_proposal' proposal.pk %}" method="POST">
        <div>
            <button>거절</button>
        </div>
    </form>
</div>


{% endif %}
{% endfor %}
{% endif %}

tour/templates/tour/tour_proposal.html
{% for group in user.groups.all %}
{% if group.name == 'tourist' %}

<div>
    <form action="{% url 'tour:proposal_tour' proposal.pk %}" method="POST">
        {% csrf_token %}
        <button>투어 요청하기</button>
    </form>
</div>

{% endif %}
{% endfor %}